version: "2"
services:
  test-backend:
    build: test/backend/
  "ist-mstrbi-p":
    build: test/customdomain_backend/
  sut:
    build: test/sut/
    links:
      - bufe-autotest-test
    volumes:
      - ./test/results:/results
    environment:
      - TEST_BASE=1
  bufe-autotest-test:
    build: 
      context: ./
      args:
        landscape: test
    #build: apache/
    #build: nginx/
    #read_only: true
    ports:
      - 80
      - 443
    #restart: always
    environment:
      - LANDSCAPE=test
      - ALLOW_DOCKER_NETS=true
    links:
      - test-backend
      - "ist-mstrbi-p"
