version: "2"
services:
  test-backend:
    build: test/backend/
  bufe-autotest-test:
    build: 
      context: ./
      args:
        landscape: test
    #build: apache/
    #build: nginx/
    #read_only: true
    ports:
      - 80:80
      - 443:443
    #restart: always
    environment:
      - LANDSCAPE=test
      - ALLOW_DOCKER_NETS=true
    links:
      - test-backend
