#!/bin/sh
#
# Simple shell script to build map files for the NGINX web router
#
# for testing outside of Docker:
#mapdir="/tmp"
#srcdir="maps/src"
# for real
mapdir="/etc/nginx/maps"
srcdir="${mapdir}/src"

# Simple helper shell functions
#
buedu () {
  echo "$1 $2 ;" >>"${mapdir}/sites.map"
}

redirect () {
  echo "$1 redirect ;" >>"${mapdir}/sites.map"
  echo "$1 $2 ;" >>"${mapdir}/redirects.map"
}

for map in sites.map redirects.map ; do
  echo "# This file generated by $0 using content in $srcdir" >"${mapdir}/$map"
done

# Now we go through all the configs in our source area and 
# do the load
#
for conf in ${srcdir}/*.conf ; do
  echo "Processing $conf"
  . "$conf"
done
