# This workflow builds the SUT Docker image and pushes it to GitHub Container Registry
# It triggers on push to main/master or on manual dispatch

name: Build and Push SUT Docker Image

on:
  push:
    branches: [ master, main ]
    paths:
      - 'test/sut/**'
      - '.github/workflows/build-sut-image.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push SUT image
        uses: docker/build-push-action@v5
        with:
          context: ./test/sut
          file: ./test/sut/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/sut:latest
